// Code generated by go-swagger; DO NOT EDIT.

package interruptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderReader is a Reader for the CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponder structure.
type CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 405:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK() *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK handles this case with default header values.

UserResource resource returned
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK struct {
	Payload *models.UserResource
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK) Error() string {
	return fmt.Sprintf("[PUT /api/interruptions/{id}/responsible][%d] customActionResponseDescriptorOctopusServerWebApiActionsInterruptionResponsibilityResponderOK  %+v", 200, o.Payload)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest() *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest handles this case with default header values.

This interruption has already been submitted, possibly by another user.
You cannot take responsibility for this interruption as you do not appear to be in any of the teams with permissions to do so. Please try again or contact your Octopus administrator.
No id parameter was provided.
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/interruptions/{id}/responsible][%d] customActionResponseDescriptorOctopusServerWebApiActionsInterruptionResponsibilityResponderBadRequest ", 400)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed() *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed handles this case with default header values.

MethodNotAllowed
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed) Error() string {
	return fmt.Sprintf("[PUT /api/interruptions/{id}/responsible][%d] customActionResponseDescriptorOctopusServerWebApiActionsInterruptionResponsibilityResponderMethodNotAllowed ", 405)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsInterruptionResponsibilityResponderMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
