// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions certificates certificate export action operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions certificates certificate export action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions certificates certificate export action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions certificates certificate export action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions certificates certificate export action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions certificates certificate export action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions certificates certificate export action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the custom action response descriptor octopus server web Api actions certificates certificate export action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) WithID(id string) *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the custom action response descriptor octopus server web Api actions certificates certificate export action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateExportActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
