// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionReader is a Reader for the CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveAction structure.
type CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK() *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK handles this case with default header values.

OK
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK) Error() string {
	return fmt.Sprintf("[POST /api/certificates/{id}/archive][%d] customActionResponseDescriptorOctopusServerWebApiActionsCertificatesCertificateArchiveActionOK ", 200)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest() *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest handles this case with default header values.

No id parameter was provided.
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/certificates/{id}/archive][%d] customActionResponseDescriptorOctopusServerWebApiActionsCertificatesCertificateArchiveActionBadRequest ", 400)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateArchiveActionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
