// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderReader is a Reader for the CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponder structure.
type CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK creates a CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK with default headers values
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK() *CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK {
	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK{}
}

/*CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK handles this case with default header values.

CertificateResource resource returned
*/
type CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK struct {
	Payload *models.CertificateResource
}

func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK) Error() string {
	return fmt.Sprintf("[GET /api/certificates/(?<idOrThumbprint>(?i)^(?!(certificate-global|certificate-azure)).*)][%d] customQueryResponseDescriptorOctopusServerWebApiActionsCertificatesCertificateByIdOrThumbprintResponderOK  %+v", 200, o.Payload)
}

func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CertificateResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest creates a CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest with default headers values
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest() *CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest {
	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest{}
}

/*CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest handles this case with default header values.

No idOrThumbprint parameter was provided.
*/
type CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest struct {
}

func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/certificates/(?<idOrThumbprint>(?i)^(?!(certificate-global|certificate-azure)).*)][%d] customQueryResponseDescriptorOctopusServerWebApiActionsCertificatesCertificateByIdOrThumbprintResponderBadRequest ", 400)
}

func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsCertificatesCertificateByIDOrThumbprintResponderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
