// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAllResponseDescriptorCertificateCertificateResourceParams creates a new ListAllResponseDescriptorCertificateCertificateResourceParams object
// with the default values initialized.
func NewListAllResponseDescriptorCertificateCertificateResourceParams() *ListAllResponseDescriptorCertificateCertificateResourceParams {

	return &ListAllResponseDescriptorCertificateCertificateResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllResponseDescriptorCertificateCertificateResourceParamsWithTimeout creates a new ListAllResponseDescriptorCertificateCertificateResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllResponseDescriptorCertificateCertificateResourceParamsWithTimeout(timeout time.Duration) *ListAllResponseDescriptorCertificateCertificateResourceParams {

	return &ListAllResponseDescriptorCertificateCertificateResourceParams{

		timeout: timeout,
	}
}

// NewListAllResponseDescriptorCertificateCertificateResourceParamsWithContext creates a new ListAllResponseDescriptorCertificateCertificateResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllResponseDescriptorCertificateCertificateResourceParamsWithContext(ctx context.Context) *ListAllResponseDescriptorCertificateCertificateResourceParams {

	return &ListAllResponseDescriptorCertificateCertificateResourceParams{

		Context: ctx,
	}
}

// NewListAllResponseDescriptorCertificateCertificateResourceParamsWithHTTPClient creates a new ListAllResponseDescriptorCertificateCertificateResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllResponseDescriptorCertificateCertificateResourceParamsWithHTTPClient(client *http.Client) *ListAllResponseDescriptorCertificateCertificateResourceParams {

	return &ListAllResponseDescriptorCertificateCertificateResourceParams{
		HTTPClient: client,
	}
}

/*ListAllResponseDescriptorCertificateCertificateResourceParams contains all the parameters to send to the API endpoint
for the list all response descriptor certificate certificate resource operation typically these are written to a http.Request
*/
type ListAllResponseDescriptorCertificateCertificateResourceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all response descriptor certificate certificate resource params
func (o *ListAllResponseDescriptorCertificateCertificateResourceParams) WithTimeout(timeout time.Duration) *ListAllResponseDescriptorCertificateCertificateResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all response descriptor certificate certificate resource params
func (o *ListAllResponseDescriptorCertificateCertificateResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all response descriptor certificate certificate resource params
func (o *ListAllResponseDescriptorCertificateCertificateResourceParams) WithContext(ctx context.Context) *ListAllResponseDescriptorCertificateCertificateResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all response descriptor certificate certificate resource params
func (o *ListAllResponseDescriptorCertificateCertificateResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all response descriptor certificate certificate resource params
func (o *ListAllResponseDescriptorCertificateCertificateResourceParams) WithHTTPClient(client *http.Client) *ListAllResponseDescriptorCertificateCertificateResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all response descriptor certificate certificate resource params
func (o *ListAllResponseDescriptorCertificateCertificateResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllResponseDescriptorCertificateCertificateResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
