// Code generated by go-swagger; DO NOT EDIT.

package certificates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// NewModifyResponseDescriptorCertificateCertificateResourceParams creates a new ModifyResponseDescriptorCertificateCertificateResourceParams object
// with the default values initialized.
func NewModifyResponseDescriptorCertificateCertificateResourceParams() *ModifyResponseDescriptorCertificateCertificateResourceParams {
	var ()
	return &ModifyResponseDescriptorCertificateCertificateResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifyResponseDescriptorCertificateCertificateResourceParamsWithTimeout creates a new ModifyResponseDescriptorCertificateCertificateResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifyResponseDescriptorCertificateCertificateResourceParamsWithTimeout(timeout time.Duration) *ModifyResponseDescriptorCertificateCertificateResourceParams {
	var ()
	return &ModifyResponseDescriptorCertificateCertificateResourceParams{

		timeout: timeout,
	}
}

// NewModifyResponseDescriptorCertificateCertificateResourceParamsWithContext creates a new ModifyResponseDescriptorCertificateCertificateResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewModifyResponseDescriptorCertificateCertificateResourceParamsWithContext(ctx context.Context) *ModifyResponseDescriptorCertificateCertificateResourceParams {
	var ()
	return &ModifyResponseDescriptorCertificateCertificateResourceParams{

		Context: ctx,
	}
}

// NewModifyResponseDescriptorCertificateCertificateResourceParamsWithHTTPClient creates a new ModifyResponseDescriptorCertificateCertificateResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModifyResponseDescriptorCertificateCertificateResourceParamsWithHTTPClient(client *http.Client) *ModifyResponseDescriptorCertificateCertificateResourceParams {
	var ()
	return &ModifyResponseDescriptorCertificateCertificateResourceParams{
		HTTPClient: client,
	}
}

/*ModifyResponseDescriptorCertificateCertificateResourceParams contains all the parameters to send to the API endpoint
for the modify response descriptor certificate certificate resource operation typically these are written to a http.Request
*/
type ModifyResponseDescriptorCertificateCertificateResourceParams struct {

	/*CertificateResource
	  The CertificateResource resource to create

	*/
	CertificateResource *models.CertificateResource
	/*ID
	  ID of the CertificateResource to modify

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) WithTimeout(timeout time.Duration) *ModifyResponseDescriptorCertificateCertificateResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) WithContext(ctx context.Context) *ModifyResponseDescriptorCertificateCertificateResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) WithHTTPClient(client *http.Client) *ModifyResponseDescriptorCertificateCertificateResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCertificateResource adds the certificateResource to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) WithCertificateResource(certificateResource *models.CertificateResource) *ModifyResponseDescriptorCertificateCertificateResourceParams {
	o.SetCertificateResource(certificateResource)
	return o
}

// SetCertificateResource adds the certificateResource to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) SetCertificateResource(certificateResource *models.CertificateResource) {
	o.CertificateResource = certificateResource
}

// WithID adds the id to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) WithID(id string) *ModifyResponseDescriptorCertificateCertificateResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the modify response descriptor certificate certificate resource params
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyResponseDescriptorCertificateCertificateResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CertificateResource != nil {
		if err := r.SetBodyParam(o.CertificateResource); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
