// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions package repository package repository delete action operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams struct {

	/*ID
	  ID of the package

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions package repository package repository delete action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions package repository package repository delete action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions package repository package repository delete action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions package repository package repository delete action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions package repository package repository delete action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions package repository package repository delete action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the custom action response descriptor octopus server web Api actions package repository package repository delete action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) WithID(id string) *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the custom action response descriptor octopus server web Api actions package repository package repository delete action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsPackageRepositoryPackageRepositoryDeleteActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
