// Code generated by go-swagger; DO NOT EDIT.

package channels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoadResponseDescriptorProjectsChannelChannelResourceParams creates a new LoadResponseDescriptorProjectsChannelChannelResourceParams object
// with the default values initialized.
func NewLoadResponseDescriptorProjectsChannelChannelResourceParams() *LoadResponseDescriptorProjectsChannelChannelResourceParams {
	var ()
	return &LoadResponseDescriptorProjectsChannelChannelResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoadResponseDescriptorProjectsChannelChannelResourceParamsWithTimeout creates a new LoadResponseDescriptorProjectsChannelChannelResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoadResponseDescriptorProjectsChannelChannelResourceParamsWithTimeout(timeout time.Duration) *LoadResponseDescriptorProjectsChannelChannelResourceParams {
	var ()
	return &LoadResponseDescriptorProjectsChannelChannelResourceParams{

		timeout: timeout,
	}
}

// NewLoadResponseDescriptorProjectsChannelChannelResourceParamsWithContext creates a new LoadResponseDescriptorProjectsChannelChannelResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoadResponseDescriptorProjectsChannelChannelResourceParamsWithContext(ctx context.Context) *LoadResponseDescriptorProjectsChannelChannelResourceParams {
	var ()
	return &LoadResponseDescriptorProjectsChannelChannelResourceParams{

		Context: ctx,
	}
}

// NewLoadResponseDescriptorProjectsChannelChannelResourceParamsWithHTTPClient creates a new LoadResponseDescriptorProjectsChannelChannelResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoadResponseDescriptorProjectsChannelChannelResourceParamsWithHTTPClient(client *http.Client) *LoadResponseDescriptorProjectsChannelChannelResourceParams {
	var ()
	return &LoadResponseDescriptorProjectsChannelChannelResourceParams{
		HTTPClient: client,
	}
}

/*LoadResponseDescriptorProjectsChannelChannelResourceParams contains all the parameters to send to the API endpoint
for the load response descriptor projects channel channel resource operation typically these are written to a http.Request
*/
type LoadResponseDescriptorProjectsChannelChannelResourceParams struct {

	/*ID
	  ID of the ChannelResource to load

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the load response descriptor projects channel channel resource params
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) WithTimeout(timeout time.Duration) *LoadResponseDescriptorProjectsChannelChannelResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the load response descriptor projects channel channel resource params
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the load response descriptor projects channel channel resource params
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) WithContext(ctx context.Context) *LoadResponseDescriptorProjectsChannelChannelResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the load response descriptor projects channel channel resource params
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the load response descriptor projects channel channel resource params
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) WithHTTPClient(client *http.Client) *LoadResponseDescriptorProjectsChannelChannelResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the load response descriptor projects channel channel resource params
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the load response descriptor projects channel channel resource params
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) WithID(id string) *LoadResponseDescriptorProjectsChannelChannelResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the load response descriptor projects channel channel resource params
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *LoadResponseDescriptorProjectsChannelChannelResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
