// Code generated by go-swagger; DO NOT EDIT.

package api_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// LoadResponseDescriptorUsersAPIKeyAPIKeyResourceReader is a Reader for the LoadResponseDescriptorUsersAPIKeyAPIKeyResource structure.
type LoadResponseDescriptorUsersAPIKeyAPIKeyResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LoadResponseDescriptorUsersAPIKeyAPIKeyResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewLoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK creates a LoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK with default headers values
func NewLoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK() *LoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK {
	return &LoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK{}
}

/*LoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK handles this case with default header values.

Load ApiKeyResource by ID
*/
type LoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK struct {
	Payload *models.APIKeyResource
}

func (o *LoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK) Error() string {
	return fmt.Sprintf("[GET /api/users/{userId}/apikeys/{id}][%d] loadResponseDescriptorUsersApiKeyApiKeyResourceOK  %+v", 200, o.Payload)
}

func (o *LoadResponseDescriptorUsersAPIKeyAPIKeyResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIKeyResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
