// Code generated by go-swagger; DO NOT EDIT.

package deployment_processes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionReader is a Reader for the CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateAction structure.
type CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK() *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK handles this case with default header values.

ReleaseTemplateResource resource returned
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK struct {
	Payload *models.ReleaseTemplateResource
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK) Error() string {
	return fmt.Sprintf("[GET /api/deploymentprocesses/{id}/template][%d] customActionResponseDescriptorOctopusServerWebApiActionsReleaseTemplateActionOK  %+v", 200, o.Payload)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReleaseTemplateResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest() *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest handles this case with default header values.

A channelId must be provided when more than one exists for that project and no default channel has been specified.
No id parameter was provided.
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/deploymentprocesses/{id}/template][%d] customActionResponseDescriptorOctopusServerWebApiActionsReleaseTemplateActionBadRequest ", 400)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseTemplateActionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
