// Code generated by go-swagger; DO NOT EDIT.

package octopus_server_nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceReader is a Reader for the ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResource structure.
type ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK creates a ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK with default headers values
func NewModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK() *ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK {
	return &ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK{}
}

/*ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK handles this case with default header values.

OctopusServerNodeResource Modified
*/
type ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK struct {
	Payload *models.OctopusServerNodeResource
}

func (o *ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK) Error() string {
	return fmt.Sprintf("[PUT /api/octopusservernodes/{id}][%d] modifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK  %+v", 200, o.Payload)
}

func (o *ModifyResponseDescriptorClusteringOctopusServerNodeOctopusServerNodeResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OctopusServerNodeResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
