// Code generated by go-swagger; DO NOT EDIT.

package reporting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions deployments Xml responder operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions deployments Xml responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions deployments Xml responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions deployments Xml responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions deployments Xml responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions deployments Xml responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions deployments Xml responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentsXMLResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
