// Code generated by go-swagger; DO NOT EDIT.

package built_in_repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions built in repository configuration update action operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions built in repository configuration update action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions built in repository configuration update action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions built in repository configuration update action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions built in repository configuration update action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions built in repository configuration update action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions built in repository configuration update action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsBuiltInRepositoryConfigurationUpdateActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
