// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAllResponseDescriptorEnvironmentsMachineMachineResourceParams creates a new ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams object
// with the default values initialized.
func NewListAllResponseDescriptorEnvironmentsMachineMachineResourceParams() *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams {

	return &ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAllResponseDescriptorEnvironmentsMachineMachineResourceParamsWithTimeout creates a new ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAllResponseDescriptorEnvironmentsMachineMachineResourceParamsWithTimeout(timeout time.Duration) *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams {

	return &ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams{

		timeout: timeout,
	}
}

// NewListAllResponseDescriptorEnvironmentsMachineMachineResourceParamsWithContext creates a new ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAllResponseDescriptorEnvironmentsMachineMachineResourceParamsWithContext(ctx context.Context) *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams {

	return &ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams{

		Context: ctx,
	}
}

// NewListAllResponseDescriptorEnvironmentsMachineMachineResourceParamsWithHTTPClient creates a new ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAllResponseDescriptorEnvironmentsMachineMachineResourceParamsWithHTTPClient(client *http.Client) *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams {

	return &ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams{
		HTTPClient: client,
	}
}

/*ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams contains all the parameters to send to the API endpoint
for the list all response descriptor environments machine machine resource operation typically these are written to a http.Request
*/
type ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list all response descriptor environments machine machine resource params
func (o *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams) WithTimeout(timeout time.Duration) *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list all response descriptor environments machine machine resource params
func (o *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list all response descriptor environments machine machine resource params
func (o *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams) WithContext(ctx context.Context) *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list all response descriptor environments machine machine resource params
func (o *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list all response descriptor environments machine machine resource params
func (o *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams) WithHTTPClient(client *http.Client) *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list all response descriptor environments machine machine resource params
func (o *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListAllResponseDescriptorEnvironmentsMachineMachineResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
