// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// NewCreateResponseDescriptorProjectsProjectProjectResourceParams creates a new CreateResponseDescriptorProjectsProjectProjectResourceParams object
// with the default values initialized.
func NewCreateResponseDescriptorProjectsProjectProjectResourceParams() *CreateResponseDescriptorProjectsProjectProjectResourceParams {
	var ()
	return &CreateResponseDescriptorProjectsProjectProjectResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateResponseDescriptorProjectsProjectProjectResourceParamsWithTimeout creates a new CreateResponseDescriptorProjectsProjectProjectResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateResponseDescriptorProjectsProjectProjectResourceParamsWithTimeout(timeout time.Duration) *CreateResponseDescriptorProjectsProjectProjectResourceParams {
	var ()
	return &CreateResponseDescriptorProjectsProjectProjectResourceParams{

		timeout: timeout,
	}
}

// NewCreateResponseDescriptorProjectsProjectProjectResourceParamsWithContext creates a new CreateResponseDescriptorProjectsProjectProjectResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateResponseDescriptorProjectsProjectProjectResourceParamsWithContext(ctx context.Context) *CreateResponseDescriptorProjectsProjectProjectResourceParams {
	var ()
	return &CreateResponseDescriptorProjectsProjectProjectResourceParams{

		Context: ctx,
	}
}

// NewCreateResponseDescriptorProjectsProjectProjectResourceParamsWithHTTPClient creates a new CreateResponseDescriptorProjectsProjectProjectResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateResponseDescriptorProjectsProjectProjectResourceParamsWithHTTPClient(client *http.Client) *CreateResponseDescriptorProjectsProjectProjectResourceParams {
	var ()
	return &CreateResponseDescriptorProjectsProjectProjectResourceParams{
		HTTPClient: client,
	}
}

/*CreateResponseDescriptorProjectsProjectProjectResourceParams contains all the parameters to send to the API endpoint
for the create response descriptor projects project project resource operation typically these are written to a http.Request
*/
type CreateResponseDescriptorProjectsProjectProjectResourceParams struct {

	/*ProjectResource
	  The ProjectResource resource to create

	*/
	ProjectResource *models.ProjectResource

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create response descriptor projects project project resource params
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) WithTimeout(timeout time.Duration) *CreateResponseDescriptorProjectsProjectProjectResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create response descriptor projects project project resource params
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create response descriptor projects project project resource params
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) WithContext(ctx context.Context) *CreateResponseDescriptorProjectsProjectProjectResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create response descriptor projects project project resource params
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create response descriptor projects project project resource params
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) WithHTTPClient(client *http.Client) *CreateResponseDescriptorProjectsProjectProjectResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create response descriptor projects project project resource params
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectResource adds the projectResource to the create response descriptor projects project project resource params
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) WithProjectResource(projectResource *models.ProjectResource) *CreateResponseDescriptorProjectsProjectProjectResourceParams {
	o.SetProjectResource(projectResource)
	return o
}

// SetProjectResource adds the projectResource to the create response descriptor projects project project resource params
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) SetProjectResource(projectResource *models.ProjectResource) {
	o.ProjectResource = projectResource
}

// WriteToRequest writes these params to a swagger request
func (o *CreateResponseDescriptorProjectsProjectProjectResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ProjectResource != nil {
		if err := r.SetBodyParam(o.ProjectResource); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
