// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions project logo get responder operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions project logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions project logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions project logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions project logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions project logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions project logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the custom action response descriptor octopus server web Api actions project logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) WithID(id string) *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the custom action response descriptor octopus server web Api actions project logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsProjectLogoGetResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
