// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams creates a new LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams object
// with the default values initialized.
func NewLoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams() *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams {
	var ()
	return &LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParamsWithTimeout creates a new LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParamsWithTimeout(timeout time.Duration) *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams {
	var ()
	return &LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams{

		timeout: timeout,
	}
}

// NewLoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParamsWithContext creates a new LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParamsWithContext(ctx context.Context) *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams {
	var ()
	return &LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams{

		Context: ctx,
	}
}

// NewLoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParamsWithHTTPClient creates a new LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParamsWithHTTPClient(client *http.Client) *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams {
	var ()
	return &LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams{
		HTTPClient: client,
	}
}

/*LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams contains all the parameters to send to the API endpoint
for the load by Id or slug response descriptor projects project project resource operation typically these are written to a http.Request
*/
type LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams struct {

	/*IDOrSlug
	  ID or slug of the ProjectResource to load

	*/
	IDOrSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the load by Id or slug response descriptor projects project project resource params
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) WithTimeout(timeout time.Duration) *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the load by Id or slug response descriptor projects project project resource params
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the load by Id or slug response descriptor projects project project resource params
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) WithContext(ctx context.Context) *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the load by Id or slug response descriptor projects project project resource params
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the load by Id or slug response descriptor projects project project resource params
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) WithHTTPClient(client *http.Client) *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the load by Id or slug response descriptor projects project project resource params
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIDOrSlug adds the iDOrSlug to the load by Id or slug response descriptor projects project project resource params
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) WithIDOrSlug(iDOrSlug string) *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams {
	o.SetIDOrSlug(iDOrSlug)
	return o
}

// SetIDOrSlug adds the idOrSlug to the load by Id or slug response descriptor projects project project resource params
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) SetIDOrSlug(iDOrSlug string) {
	o.IDOrSlug = iDOrSlug
}

// WriteToRequest writes these params to a swagger request
func (o *LoadByIDOrSlugResponseDescriptorProjectsProjectProjectResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param idOrSlug
	if err := r.SetPathParam("idOrSlug", o.IDOrSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
