// Code generated by go-swagger; DO NOT EDIT.

package tag_sets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// ModifyResponseDescriptorTagSetsTagSetTagSetResourceReader is a Reader for the ModifyResponseDescriptorTagSetsTagSetTagSetResource structure.
type ModifyResponseDescriptorTagSetsTagSetTagSetResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyResponseDescriptorTagSetsTagSetTagSetResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyResponseDescriptorTagSetsTagSetTagSetResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyResponseDescriptorTagSetsTagSetTagSetResourceOK creates a ModifyResponseDescriptorTagSetsTagSetTagSetResourceOK with default headers values
func NewModifyResponseDescriptorTagSetsTagSetTagSetResourceOK() *ModifyResponseDescriptorTagSetsTagSetTagSetResourceOK {
	return &ModifyResponseDescriptorTagSetsTagSetTagSetResourceOK{}
}

/*ModifyResponseDescriptorTagSetsTagSetTagSetResourceOK handles this case with default header values.

TagSetResource Modified
*/
type ModifyResponseDescriptorTagSetsTagSetTagSetResourceOK struct {
	Payload *models.TagSetResource
}

func (o *ModifyResponseDescriptorTagSetsTagSetTagSetResourceOK) Error() string {
	return fmt.Sprintf("[PUT /api/tagsets/{id}][%d] modifyResponseDescriptorTagSetsTagSetTagSetResourceOK  %+v", 200, o.Payload)
}

func (o *ModifyResponseDescriptorTagSetsTagSetTagSetResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TagSetResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
