// Code generated by go-swagger; DO NOT EDIT.

package user_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CreateResponseDescriptorUsersUserRoleUserRoleResourceReader is a Reader for the CreateResponseDescriptorUsersUserRoleUserRoleResource structure.
type CreateResponseDescriptorUsersUserRoleUserRoleResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateResponseDescriptorUsersUserRoleUserRoleResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateResponseDescriptorUsersUserRoleUserRoleResourceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateResponseDescriptorUsersUserRoleUserRoleResourceCreated creates a CreateResponseDescriptorUsersUserRoleUserRoleResourceCreated with default headers values
func NewCreateResponseDescriptorUsersUserRoleUserRoleResourceCreated() *CreateResponseDescriptorUsersUserRoleUserRoleResourceCreated {
	return &CreateResponseDescriptorUsersUserRoleUserRoleResourceCreated{}
}

/*CreateResponseDescriptorUsersUserRoleUserRoleResourceCreated handles this case with default header values.

UserRoleResource Created
*/
type CreateResponseDescriptorUsersUserRoleUserRoleResourceCreated struct {
	Payload *models.UserRoleResource
}

func (o *CreateResponseDescriptorUsersUserRoleUserRoleResourceCreated) Error() string {
	return fmt.Sprintf("[POST /api/userroles][%d] createResponseDescriptorUsersUserRoleUserRoleResourceCreated  %+v", 201, o.Payload)
}

func (o *CreateResponseDescriptorUsersUserRoleUserRoleResourceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserRoleResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
