// Code generated by go-swagger; DO NOT EDIT.

package action_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions action template logo get responder operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams struct {

	/*ID
	  ID of the resource

	*/
	ID string
	/*TypeOrID
	  Action Type or ID of the action type logo

	*/
	TypeOrID string
	/*Version
	  Version of the action type logo

	*/
	Version int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) WithID(id string) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) SetID(id string) {
	o.ID = id
}

// WithTypeOrID adds the typeOrID to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) WithTypeOrID(typeOrID string) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	o.SetTypeOrID(typeOrID)
	return o
}

// SetTypeOrID adds the typeOrId to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) SetTypeOrID(typeOrID string) {
	o.TypeOrID = typeOrID
}

// WithVersion adds the version to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) WithVersion(version int32) *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the custom action response descriptor octopus server web Api actions action template logo get responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) SetVersion(version int32) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsActionTemplateLogoGetResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param typeOrId
	if err := r.SetPathParam("typeOrId", o.TypeOrID); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", swag.FormatInt32(o.Version)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
