// Code generated by go-swagger; DO NOT EDIT.

package tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderReader is a Reader for the CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponder structure.
type CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK() *CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK handles this case with default header values.

TaskResource resource returned
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK struct {
	Payload *models.TaskResource
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK) Error() string {
	return fmt.Sprintf("[POST /api/tasks/{id}/cancel][%d] customActionResponseDescriptorOctopusServerWebApiActionsTaskCancelResponderOK  %+v", 200, o.Payload)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest() *CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest handles this case with default header values.

No id parameter was provided.
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/tasks/{id}/cancel][%d] customActionResponseDescriptorOctopusServerWebApiActionsTaskCancelResponderBadRequest ", 400)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTaskCancelResponderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
