// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CreateResponseDescriptorUsersInvitationInvitationResourceReader is a Reader for the CreateResponseDescriptorUsersInvitationInvitationResource structure.
type CreateResponseDescriptorUsersInvitationInvitationResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateResponseDescriptorUsersInvitationInvitationResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateResponseDescriptorUsersInvitationInvitationResourceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateResponseDescriptorUsersInvitationInvitationResourceCreated creates a CreateResponseDescriptorUsersInvitationInvitationResourceCreated with default headers values
func NewCreateResponseDescriptorUsersInvitationInvitationResourceCreated() *CreateResponseDescriptorUsersInvitationInvitationResourceCreated {
	return &CreateResponseDescriptorUsersInvitationInvitationResourceCreated{}
}

/*CreateResponseDescriptorUsersInvitationInvitationResourceCreated handles this case with default header values.

InvitationResource Created
*/
type CreateResponseDescriptorUsersInvitationInvitationResourceCreated struct {
	Payload *models.InvitationResource
}

func (o *CreateResponseDescriptorUsersInvitationInvitationResourceCreated) Error() string {
	return fmt.Sprintf("[POST /api/users/invitations][%d] createResponseDescriptorUsersInvitationInvitationResourceCreated  %+v", 201, o.Payload)
}

func (o *CreateResponseDescriptorUsersInvitationInvitationResourceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InvitationResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
