// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions variables scoped to environment responder operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions variables scoped to environment responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions variables scoped to environment responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions variables scoped to environment responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions variables scoped to environment responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions variables scoped to environment responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions variables scoped to environment responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the custom action response descriptor octopus server web Api actions variables scoped to environment responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) WithID(id string) *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the custom action response descriptor octopus server web Api actions variables scoped to environment responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsVariablesScopedToEnvironmentResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
