// Code generated by go-swagger; DO NOT EDIT.

package environments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceReader is a Reader for the ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResource structure.
type ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK creates a ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK with default headers values
func NewModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK() *ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK {
	return &ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK{}
}

/*ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK handles this case with default header values.

EnvironmentResource Modified
*/
type ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK struct {
	Payload *models.EnvironmentResource
}

func (o *ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK) Error() string {
	return fmt.Sprintf("[PUT /api/environments/{id}][%d] modifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK  %+v", 200, o.Payload)
}

func (o *ModifyResponseDescriptorEnvironmentsDeploymentEnvironmentEnvironmentResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EnvironmentResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
