// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CreateResponseDescriptorTenantsTenantTenantResourceReader is a Reader for the CreateResponseDescriptorTenantsTenantTenantResource structure.
type CreateResponseDescriptorTenantsTenantTenantResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateResponseDescriptorTenantsTenantTenantResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateResponseDescriptorTenantsTenantTenantResourceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateResponseDescriptorTenantsTenantTenantResourceCreated creates a CreateResponseDescriptorTenantsTenantTenantResourceCreated with default headers values
func NewCreateResponseDescriptorTenantsTenantTenantResourceCreated() *CreateResponseDescriptorTenantsTenantTenantResourceCreated {
	return &CreateResponseDescriptorTenantsTenantTenantResourceCreated{}
}

/*CreateResponseDescriptorTenantsTenantTenantResourceCreated handles this case with default header values.

TenantResource Created
*/
type CreateResponseDescriptorTenantsTenantTenantResourceCreated struct {
	Payload *models.TenantResource
}

func (o *CreateResponseDescriptorTenantsTenantTenantResourceCreated) Error() string {
	return fmt.Sprintf("[POST /api/tenants][%d] createResponseDescriptorTenantsTenantTenantResourceCreated  %+v", 201, o.Payload)
}

func (o *CreateResponseDescriptorTenantsTenantTenantResourceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
