// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams {
	var ()
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions tenant logo put responder operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams struct {

	/*ID
	  ID of the resource

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions tenant logo put responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions tenant logo put responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions tenant logo put responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions tenant logo put responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions tenant logo put responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions tenant logo put responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the custom action response descriptor octopus server web Api actions tenant logo put responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) WithID(id string) *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the custom action response descriptor octopus server web Api actions tenant logo put responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
