// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderReader is a Reader for the CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponder structure.
type CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK() *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK handles this case with default header values.

OK
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK) Error() string {
	return fmt.Sprintf("[PUT /api/tenants/{id}/logo][%d] customActionResponseDescriptorOctopusServerWebApiActionsTenantLogoPutResponderOK ", 200)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest() *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest handles this case with default header values.

Action rejected.
Invalid image provided.
No id parameter was provided.
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest) Error() string {
	return fmt.Sprintf("[PUT /api/tenants/{id}/logo][%d] customActionResponseDescriptorOctopusServerWebApiActionsTenantLogoPutResponderBadRequest ", 400)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsTenantLogoPutResponderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
