// Code generated by go-swagger; DO NOT EDIT.

package tenants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// ModifyResponseDescriptorTenantsTenantTenantResourceReader is a Reader for the ModifyResponseDescriptorTenantsTenantTenantResource structure.
type ModifyResponseDescriptorTenantsTenantTenantResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyResponseDescriptorTenantsTenantTenantResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyResponseDescriptorTenantsTenantTenantResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyResponseDescriptorTenantsTenantTenantResourceOK creates a ModifyResponseDescriptorTenantsTenantTenantResourceOK with default headers values
func NewModifyResponseDescriptorTenantsTenantTenantResourceOK() *ModifyResponseDescriptorTenantsTenantTenantResourceOK {
	return &ModifyResponseDescriptorTenantsTenantTenantResourceOK{}
}

/*ModifyResponseDescriptorTenantsTenantTenantResourceOK handles this case with default header values.

TenantResource Modified
*/
type ModifyResponseDescriptorTenantsTenantTenantResourceOK struct {
	Payload *models.TenantResource
}

func (o *ModifyResponseDescriptorTenantsTenantTenantResourceOK) Error() string {
	return fmt.Sprintf("[PUT /api/tenants/{id}][%d] modifyResponseDescriptorTenantsTenantTenantResourceOK  %+v", 200, o.Payload)
}

func (o *ModifyResponseDescriptorTenantsTenantTenantResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TenantResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
