// Code generated by go-swagger; DO NOT EDIT.

package machine_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams creates a new ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams object
// with the default values initialized.
func NewChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams() *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	var ()
	return &ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParamsWithTimeout creates a new ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParamsWithTimeout(timeout time.Duration) *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	var ()
	return &ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams{

		timeout: timeout,
	}
}

// NewChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParamsWithContext creates a new ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParamsWithContext(ctx context.Context) *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	var ()
	return &ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams{

		Context: ctx,
	}
}

// NewChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParamsWithHTTPClient creates a new ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParamsWithHTTPClient(client *http.Client) *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	var ()
	return &ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams{
		HTTPClient: client,
	}
}

/*ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams contains all the parameters to send to the API endpoint
for the child index response descriptor policies machine policy environments machine machine policy resource machine resource operation typically these are written to a http.Request
*/
type ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams struct {

	/*Skip
	  Number of items to skip

	*/
	Skip *int32
	/*Take
	  Number of items to take

	*/
	Take *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) WithTimeout(timeout time.Duration) *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) WithContext(ctx context.Context) *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) WithHTTPClient(client *http.Client) *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSkip adds the skip to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) WithSkip(skip *int32) *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) SetSkip(skip *int32) {
	o.Skip = skip
}

// WithTake adds the take to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) WithTake(take *int32) *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams {
	o.SetTake(take)
	return o
}

// SetTake adds the take to the child index response descriptor policies machine policy environments machine machine policy resource machine resource params
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) SetTake(take *int32) {
	o.Take = take
}

// WriteToRequest writes these params to a swagger request
func (o *ChildIndexResponseDescriptorPoliciesMachinePolicyEnvironmentsMachineMachinePolicyResourceMachineResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Skip != nil {

		// query param skip
		var qrSkip int32
		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt32(qrSkip)
		if qSkip != "" {
			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}

	}

	if o.Take != nil {

		// query param take
		var qrTake int32
		if o.Take != nil {
			qrTake = *o.Take
		}
		qTake := swag.FormatInt32(qrTake)
		if qTake != "" {
			if err := r.SetQueryParam("take", qTake); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
