// Code generated by go-swagger; DO NOT EDIT.

package machine_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams creates a new LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams object
// with the default values initialized.
func NewLoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams() *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams {
	var ()
	return &LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParamsWithTimeout creates a new LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParamsWithTimeout(timeout time.Duration) *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams {
	var ()
	return &LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams{

		timeout: timeout,
	}
}

// NewLoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParamsWithContext creates a new LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParamsWithContext(ctx context.Context) *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams {
	var ()
	return &LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams{

		Context: ctx,
	}
}

// NewLoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParamsWithHTTPClient creates a new LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParamsWithHTTPClient(client *http.Client) *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams {
	var ()
	return &LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams{
		HTTPClient: client,
	}
}

/*LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams contains all the parameters to send to the API endpoint
for the load response descriptor policies machine policy machine policy resource operation typically these are written to a http.Request
*/
type LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams struct {

	/*ID
	  ID of the MachinePolicyResource to load

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the load response descriptor policies machine policy machine policy resource params
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) WithTimeout(timeout time.Duration) *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the load response descriptor policies machine policy machine policy resource params
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the load response descriptor policies machine policy machine policy resource params
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) WithContext(ctx context.Context) *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the load response descriptor policies machine policy machine policy resource params
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the load response descriptor policies machine policy machine policy resource params
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) WithHTTPClient(client *http.Client) *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the load response descriptor policies machine policy machine policy resource params
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the load response descriptor policies machine policy machine policy resource params
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) WithID(id string) *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the load response descriptor policies machine policy machine policy resource params
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *LoadResponseDescriptorPoliciesMachinePolicyMachinePolicyResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
