// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceReader is a Reader for the DeleteOnBackgroundResponseDescriptorFeedFeedFeedResource structure.
type DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK creates a DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK with default headers values
func NewDeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK() *DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK {
	return &DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK{}
}

/*DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK handles this case with default header values.

FeedResource Deleted
*/
type DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK struct {
	Payload *models.TaskResource
}

func (o *DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK) Error() string {
	return fmt.Sprintf("[DELETE /api/feeds/{id}][%d] deleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK  %+v", 200, o.Payload)
}

func (o *DeleteOnBackgroundResponseDescriptorFeedFeedFeedResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TaskResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
