// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderReader is a Reader for the CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponder structure.
type CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK() *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK handles this case with default header values.

ReleaseResource resource returned
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK struct {
	Payload *models.ReleaseResource
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK) Error() string {
	return fmt.Sprintf("[GET /api/projects/{id}/releases/{version}][%d] customActionResponseDescriptorOctopusServerWebApiActionsReleaseByProjectAndVersionResponderOK  %+v", 200, o.Payload)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReleaseResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest() *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest handles this case with default header values.

No version parameter was provided.
No id parameter was provided.
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/projects/{id}/releases/{version}][%d] customActionResponseDescriptorOctopusServerWebApiActionsReleaseByProjectAndVersionResponderBadRequest ", 400)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsReleaseByProjectAndVersionResponderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
