// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderReader is a Reader for the CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponder structure.
type CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK() *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK handles this case with default header values.

DefectResource resource returned
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK struct {
	Payload *models.DefectResource
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK) Error() string {
	return fmt.Sprintf("[POST /api/releases/{id}/defects][%d] customActionResponseDescriptorOctopusServerWebApiActionsDefectReportedResponderOK  %+v", 200, o.Payload)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefectResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest() *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest handles this case with default header values.

You must provide a description.
An unresolved defect already exists for this release.
No request body was supplied.
No id parameter was provided.
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/releases/{id}/defects][%d] customActionResponseDescriptorOctopusServerWebApiActionsDefectReportedResponderBadRequest ", 400)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectReportedResponderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
