// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderReader is a Reader for the CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponder structure.
type CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK() *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK handles this case with default header values.

DefectResource resource returned
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK struct {
	Payload *models.DefectResource
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK) Error() string {
	return fmt.Sprintf("[POST /api/releases/{id}/defects/resolve][%d] customActionResponseDescriptorOctopusServerWebApiActionsDefectResolvedResponderOK  %+v", 200, o.Payload)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefectResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest creates a CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest with default headers values
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest() *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest {
	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest{}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest handles this case with default header values.

Index refers to an invalid defect.
Defect has already been resolved.
No id parameter was provided.
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest struct {
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/releases/{id}/defects/resolve][%d] customActionResponseDescriptorOctopusServerWebApiActionsDefectResolvedResponderBadRequest ", 400)
}

func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDefectResolvedResponderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
