// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams creates a new DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams object
// with the default values initialized.
func NewDeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams() *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams {
	var ()
	return &DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParamsWithTimeout creates a new DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParamsWithTimeout(timeout time.Duration) *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams {
	var ()
	return &DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams{

		timeout: timeout,
	}
}

// NewDeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParamsWithContext creates a new DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParamsWithContext(ctx context.Context) *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams {
	var ()
	return &DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams{

		Context: ctx,
	}
}

// NewDeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParamsWithHTTPClient creates a new DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParamsWithHTTPClient(client *http.Client) *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams {
	var ()
	return &DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams{
		HTTPClient: client,
	}
}

/*DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams contains all the parameters to send to the API endpoint
for the delete on background response descriptor projects release release resource operation typically these are written to a http.Request
*/
type DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams struct {

	/*ID
	  ID of the ReleaseResource to delete

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete on background response descriptor projects release release resource params
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) WithTimeout(timeout time.Duration) *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete on background response descriptor projects release release resource params
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete on background response descriptor projects release release resource params
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) WithContext(ctx context.Context) *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete on background response descriptor projects release release resource params
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete on background response descriptor projects release release resource params
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) WithHTTPClient(client *http.Client) *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete on background response descriptor projects release release resource params
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete on background response descriptor projects release release resource params
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) WithID(id string) *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete on background response descriptor projects release release resource params
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOnBackgroundResponseDescriptorProjectsReleaseReleaseResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
