// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// NewModifyResponseDescriptorProjectsReleaseReleaseResourceParams creates a new ModifyResponseDescriptorProjectsReleaseReleaseResourceParams object
// with the default values initialized.
func NewModifyResponseDescriptorProjectsReleaseReleaseResourceParams() *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	var ()
	return &ModifyResponseDescriptorProjectsReleaseReleaseResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifyResponseDescriptorProjectsReleaseReleaseResourceParamsWithTimeout creates a new ModifyResponseDescriptorProjectsReleaseReleaseResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifyResponseDescriptorProjectsReleaseReleaseResourceParamsWithTimeout(timeout time.Duration) *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	var ()
	return &ModifyResponseDescriptorProjectsReleaseReleaseResourceParams{

		timeout: timeout,
	}
}

// NewModifyResponseDescriptorProjectsReleaseReleaseResourceParamsWithContext creates a new ModifyResponseDescriptorProjectsReleaseReleaseResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewModifyResponseDescriptorProjectsReleaseReleaseResourceParamsWithContext(ctx context.Context) *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	var ()
	return &ModifyResponseDescriptorProjectsReleaseReleaseResourceParams{

		Context: ctx,
	}
}

// NewModifyResponseDescriptorProjectsReleaseReleaseResourceParamsWithHTTPClient creates a new ModifyResponseDescriptorProjectsReleaseReleaseResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewModifyResponseDescriptorProjectsReleaseReleaseResourceParamsWithHTTPClient(client *http.Client) *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	var ()
	return &ModifyResponseDescriptorProjectsReleaseReleaseResourceParams{
		HTTPClient: client,
	}
}

/*ModifyResponseDescriptorProjectsReleaseReleaseResourceParams contains all the parameters to send to the API endpoint
for the modify response descriptor projects release release resource operation typically these are written to a http.Request
*/
type ModifyResponseDescriptorProjectsReleaseReleaseResourceParams struct {

	/*ReleaseResource
	  The ReleaseResource resource to create

	*/
	ReleaseResource *models.ReleaseResource
	/*ID
	  ID of the ReleaseResource to modify

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) WithTimeout(timeout time.Duration) *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) WithContext(ctx context.Context) *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) WithHTTPClient(client *http.Client) *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReleaseResource adds the releaseResource to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) WithReleaseResource(releaseResource *models.ReleaseResource) *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetReleaseResource(releaseResource)
	return o
}

// SetReleaseResource adds the releaseResource to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) SetReleaseResource(releaseResource *models.ReleaseResource) {
	o.ReleaseResource = releaseResource
}

// WithID adds the id to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) WithID(id string) *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the modify response descriptor projects release release resource params
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyResponseDescriptorProjectsReleaseReleaseResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ReleaseResource != nil {
		if err := r.SetBodyParam(o.ReleaseResource); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
