// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// IndexResponseDescriptorUsersTeamTeamResourceReader is a Reader for the IndexResponseDescriptorUsersTeamTeamResource structure.
type IndexResponseDescriptorUsersTeamTeamResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexResponseDescriptorUsersTeamTeamResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIndexResponseDescriptorUsersTeamTeamResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIndexResponseDescriptorUsersTeamTeamResourceOK creates a IndexResponseDescriptorUsersTeamTeamResourceOK with default headers values
func NewIndexResponseDescriptorUsersTeamTeamResourceOK() *IndexResponseDescriptorUsersTeamTeamResourceOK {
	return &IndexResponseDescriptorUsersTeamTeamResourceOK{}
}

/*IndexResponseDescriptorUsersTeamTeamResourceOK handles this case with default header values.

Load TeamResource collection
*/
type IndexResponseDescriptorUsersTeamTeamResourceOK struct {
	Payload *models.ResourceCollectionTeamResource
}

func (o *IndexResponseDescriptorUsersTeamTeamResourceOK) Error() string {
	return fmt.Sprintf("[GET /api/teams][%d] indexResponseDescriptorUsersTeamTeamResourceOK  %+v", 200, o.Payload)
}

func (o *IndexResponseDescriptorUsersTeamTeamResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceCollectionTeamResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
