// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// ListAllResponseDescriptorUsersTeamTeamResourceReader is a Reader for the ListAllResponseDescriptorUsersTeamTeamResource structure.
type ListAllResponseDescriptorUsersTeamTeamResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAllResponseDescriptorUsersTeamTeamResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListAllResponseDescriptorUsersTeamTeamResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListAllResponseDescriptorUsersTeamTeamResourceOK creates a ListAllResponseDescriptorUsersTeamTeamResourceOK with default headers values
func NewListAllResponseDescriptorUsersTeamTeamResourceOK() *ListAllResponseDescriptorUsersTeamTeamResourceOK {
	return &ListAllResponseDescriptorUsersTeamTeamResourceOK{}
}

/*ListAllResponseDescriptorUsersTeamTeamResourceOK handles this case with default header values.

Load all TeamResource
*/
type ListAllResponseDescriptorUsersTeamTeamResourceOK struct {
	Payload []*models.TeamResource
}

func (o *ListAllResponseDescriptorUsersTeamTeamResourceOK) Error() string {
	return fmt.Sprintf("[GET /api/teams/all][%d] listAllResponseDescriptorUsersTeamTeamResourceOK  %+v", 200, o.Payload)
}

func (o *ListAllResponseDescriptorUsersTeamTeamResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
