// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions scheduler stop responder operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions scheduler stop responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions scheduler stop responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions scheduler stop responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions scheduler stop responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions scheduler stop responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions scheduler stop responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsSchedulerStopResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
