// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams creates a new CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams object
// with the default values initialized.
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams() *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams {

	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParamsWithTimeout creates a new CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParamsWithTimeout(timeout time.Duration) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams {

	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams{

		timeout: timeout,
	}
}

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParamsWithContext creates a new CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParamsWithContext(ctx context.Context) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams {

	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams{

		Context: ctx,
	}
}

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParamsWithHTTPClient creates a new CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParamsWithHTTPClient(client *http.Client) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams {

	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams{
		HTTPClient: client,
	}
}

/*CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams contains all the parameters to send to the API endpoint
for the custom query response descriptor octopus server web Api actions list server timezones responder operation typically these are written to a http.Request
*/
type CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom query response descriptor octopus server web Api actions list server timezones responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams) WithTimeout(timeout time.Duration) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom query response descriptor octopus server web Api actions list server timezones responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom query response descriptor octopus server web Api actions list server timezones responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams) WithContext(ctx context.Context) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom query response descriptor octopus server web Api actions list server timezones responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom query response descriptor octopus server web Api actions list server timezones responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams) WithHTTPClient(client *http.Client) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom query response descriptor octopus server web Api actions list server timezones responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsListServerTimezonesResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
