// Code generated by go-swagger; DO NOT EDIT.

package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams creates a new CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams() *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api nu get built in feed stats responder operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api nu get built in feed stats responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api nu get built in feed stats responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api nu get built in feed stats responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api nu get built in feed stats responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api nu get built in feed stats responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api nu get built in feed stats responder params
func (o *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPINuGetBuiltInFeedStatsResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
