// Code generated by go-swagger; DO NOT EDIT.

package subscription

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceReader is a Reader for the ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResource structure.
type ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK creates a ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK with default headers values
func NewListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK() *ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK {
	return &ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK{}
}

/*ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK handles this case with default header values.

Load all SubscriptionResource
*/
type ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK struct {
	Payload []*models.SubscriptionResource
}

func (o *ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK) Error() string {
	return fmt.Sprintf("[GET /api/subscriptions/all][%d] listAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK  %+v", 200, o.Payload)
}

func (o *ListAllResponseDescriptorSubscriptionsSubscriptionSubscriptionResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
