// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams creates a new IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams object
// with the default values initialized.
func NewIndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams() *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	var ()
	return &IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParamsWithTimeout creates a new IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParamsWithTimeout(timeout time.Duration) *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	var ()
	return &IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams{

		timeout: timeout,
	}
}

// NewIndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParamsWithContext creates a new IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewIndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParamsWithContext(ctx context.Context) *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	var ()
	return &IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams{

		Context: ctx,
	}
}

// NewIndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParamsWithHTTPClient creates a new IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParamsWithHTTPClient(client *http.Client) *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	var ()
	return &IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams{
		HTTPClient: client,
	}
}

/*IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams contains all the parameters to send to the API endpoint
for the index response descriptor environments accounts account accounts account resource operation typically these are written to a http.Request
*/
type IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams struct {

	/*Skip
	  Number of items to skip

	*/
	Skip *int32
	/*Take
	  Number of items to take

	*/
	Take *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) WithTimeout(timeout time.Duration) *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) WithContext(ctx context.Context) *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) WithHTTPClient(client *http.Client) *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSkip adds the skip to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) WithSkip(skip *int32) *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) SetSkip(skip *int32) {
	o.Skip = skip
}

// WithTake adds the take to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) WithTake(take *int32) *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams {
	o.SetTake(take)
	return o
}

// SetTake adds the take to the index response descriptor environments accounts account accounts account resource params
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) SetTake(take *int32) {
	o.Take = take
}

// WriteToRequest writes these params to a swagger request
func (o *IndexResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Skip != nil {

		// query param skip
		var qrSkip int32
		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt32(qrSkip)
		if qSkip != "" {
			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}

	}

	if o.Take != nil {

		// query param take
		var qrTake int32
		if o.Take != nil {
			qrTake = *o.Take
		}
		qTake := swag.FormatInt32(qrTake)
		if qTake != "" {
			if err := r.SetQueryParam("take", qTake); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
