// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/MattHodge/go-octopusdeploy/models"
)

// ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceReader is a Reader for the ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResource structure.
type ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK creates a ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK with default headers values
func NewModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK() *ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK {
	return &ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK{}
}

/*ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK handles this case with default header values.

AccountResource Modified
*/
type ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK struct {
	Payload *models.AccountResource
}

func (o *ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK) Error() string {
	return fmt.Sprintf("[PUT /api/accounts/{id}][%d] modifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK  %+v", 200, o.Payload)
}

func (o *ModifyResponseDescriptorEnvironmentsAccountsAccountAccountsAccountResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
