// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams object
// with the default values initialized.
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams() *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParamsWithTimeout creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParamsWithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams{

		timeout: timeout,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParamsWithContext creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParamsWithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams{

		Context: ctx,
	}
}

// NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParamsWithHTTPClient creates a new CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParamsWithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams {

	return &CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams{
		HTTPClient: client,
	}
}

/*CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams contains all the parameters to send to the API endpoint
for the custom action response descriptor octopus server web Api actions deployment create action operation typically these are written to a http.Request
*/
type CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom action response descriptor octopus server web Api actions deployment create action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams) WithTimeout(timeout time.Duration) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom action response descriptor octopus server web Api actions deployment create action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom action response descriptor octopus server web Api actions deployment create action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams) WithContext(ctx context.Context) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom action response descriptor octopus server web Api actions deployment create action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions deployment create action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams) WithHTTPClient(client *http.Client) *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom action response descriptor octopus server web Api actions deployment create action params
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomActionResponseDescriptorOctopusServerWebAPIActionsDeploymentCreateActionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
