// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams creates a new CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams object
// with the default values initialized.
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams() *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams {

	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParamsWithTimeout creates a new CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParamsWithTimeout(timeout time.Duration) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams {

	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams{

		timeout: timeout,
	}
}

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParamsWithContext creates a new CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParamsWithContext(ctx context.Context) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams {

	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams{

		Context: ctx,
	}
}

// NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParamsWithHTTPClient creates a new CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParamsWithHTTPClient(client *http.Client) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams {

	return &CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams{
		HTTPClient: client,
	}
}

/*CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams contains all the parameters to send to the API endpoint
for the custom query response descriptor octopus server web Api actions deployments query responder operation typically these are written to a http.Request
*/
type CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the custom query response descriptor octopus server web Api actions deployments query responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams) WithTimeout(timeout time.Duration) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom query response descriptor octopus server web Api actions deployments query responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom query response descriptor octopus server web Api actions deployments query responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams) WithContext(ctx context.Context) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom query response descriptor octopus server web Api actions deployments query responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom query response descriptor octopus server web Api actions deployments query responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams) WithHTTPClient(client *http.Client) *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom query response descriptor octopus server web Api actions deployments query responder params
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CustomQueryResponseDescriptorOctopusServerWebAPIActionsDeploymentsQueryResponderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
