// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoadResponseDescriptorProjectsDeploymentDeploymentResourceParams creates a new LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams object
// with the default values initialized.
func NewLoadResponseDescriptorProjectsDeploymentDeploymentResourceParams() *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams {
	var ()
	return &LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoadResponseDescriptorProjectsDeploymentDeploymentResourceParamsWithTimeout creates a new LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoadResponseDescriptorProjectsDeploymentDeploymentResourceParamsWithTimeout(timeout time.Duration) *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams {
	var ()
	return &LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams{

		timeout: timeout,
	}
}

// NewLoadResponseDescriptorProjectsDeploymentDeploymentResourceParamsWithContext creates a new LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoadResponseDescriptorProjectsDeploymentDeploymentResourceParamsWithContext(ctx context.Context) *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams {
	var ()
	return &LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams{

		Context: ctx,
	}
}

// NewLoadResponseDescriptorProjectsDeploymentDeploymentResourceParamsWithHTTPClient creates a new LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoadResponseDescriptorProjectsDeploymentDeploymentResourceParamsWithHTTPClient(client *http.Client) *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams {
	var ()
	return &LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams{
		HTTPClient: client,
	}
}

/*LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams contains all the parameters to send to the API endpoint
for the load response descriptor projects deployment deployment resource operation typically these are written to a http.Request
*/
type LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams struct {

	/*ID
	  ID of the DeploymentResource to load

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the load response descriptor projects deployment deployment resource params
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) WithTimeout(timeout time.Duration) *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the load response descriptor projects deployment deployment resource params
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the load response descriptor projects deployment deployment resource params
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) WithContext(ctx context.Context) *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the load response descriptor projects deployment deployment resource params
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the load response descriptor projects deployment deployment resource params
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) WithHTTPClient(client *http.Client) *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the load response descriptor projects deployment deployment resource params
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the load response descriptor projects deployment deployment resource params
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) WithID(id string) *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the load response descriptor projects deployment deployment resource params
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *LoadResponseDescriptorProjectsDeploymentDeploymentResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
