// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ActivityLogTreeNode activity log tree node
// swagger:model ActivityLogTreeNode
type ActivityLogTreeNode struct {

	// children
	// Read Only: true
	Children []*ActivityLogTreeNode `json:"Children"`

	// ended
	// Format: date-time
	Ended strfmt.DateTime `json:"Ended,omitempty"`

	// Id
	ID string `json:"Id,omitempty"`

	// log elements
	// Read Only: true
	LogElements []*ActivityLogEntry `json:"LogElements"`

	// name
	Name string `json:"Name,omitempty"`

	// progress message
	ProgressMessage string `json:"ProgressMessage,omitempty"`

	// progress percentage
	ProgressPercentage int32 `json:"ProgressPercentage,omitempty"`

	// show at summary level
	// Read Only: true
	ShowAtSummaryLevel *bool `json:"ShowAtSummaryLevel,omitempty"`

	// started
	// Format: date-time
	Started strfmt.DateTime `json:"Started,omitempty"`

	// status
	// Enum: [Pending Running Success Failed Skipped SuccessWithWarning Canceled]
	Status int32 `json:"Status,omitempty"`
}

// Validate validates this activity log tree node
func (m *ActivityLogTreeNode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChildren(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnded(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogElements(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStarted(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActivityLogTreeNode) validateChildren(formats strfmt.Registry) error {

	if swag.IsZero(m.Children) { // not required
		return nil
	}

	for i := 0; i < len(m.Children); i++ {
		if swag.IsZero(m.Children[i]) { // not required
			continue
		}

		if m.Children[i] != nil {
			if err := m.Children[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Children" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ActivityLogTreeNode) validateEnded(formats strfmt.Registry) error {

	if swag.IsZero(m.Ended) { // not required
		return nil
	}

	if err := validate.FormatOf("Ended", "body", "date-time", m.Ended.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ActivityLogTreeNode) validateLogElements(formats strfmt.Registry) error {

	if swag.IsZero(m.LogElements) { // not required
		return nil
	}

	for i := 0; i < len(m.LogElements); i++ {
		if swag.IsZero(m.LogElements[i]) { // not required
			continue
		}

		if m.LogElements[i] != nil {
			if err := m.LogElements[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("LogElements" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ActivityLogTreeNode) validateStarted(formats strfmt.Registry) error {

	if swag.IsZero(m.Started) { // not required
		return nil
	}

	if err := validate.FormatOf("Started", "body", "date-time", m.Started.String(), formats); err != nil {
		return err
	}

	return nil
}

var activityLogTreeNodeTypeStatusPropEnum []interface{}

func init() {
	var res []int32
	if err := json.Unmarshal([]byte(`["Pending","Running","Success","Failed","Skipped","SuccessWithWarning","Canceled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		activityLogTreeNodeTypeStatusPropEnum = append(activityLogTreeNodeTypeStatusPropEnum, v)
	}
}

// prop value enum
func (m *ActivityLogTreeNode) validateStatusEnum(path, location string, value int32) error {
	if err := validate.Enum(path, location, value, activityLogTreeNodeTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ActivityLogTreeNode) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("Status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActivityLogTreeNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActivityLogTreeNode) UnmarshalBinary(b []byte) error {
	var res ActivityLogTreeNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
