// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LicenseStatusResource license status resource
// swagger:model LicenseStatusResource
type LicenseStatusResource struct {

	// Id
	ID string `json:"Id,omitempty"`

	// is compliant
	IsCompliant bool `json:"IsCompliant,omitempty"`

	// is grandfathered
	IsGrandfathered bool `json:"IsGrandfathered,omitempty"`

	// last modified by
	LastModifiedBy string `json:"LastModifiedBy,omitempty"`

	// last modified on
	// Format: date-time
	LastModifiedOn strfmt.DateTime `json:"LastModifiedOn,omitempty"`

	// links
	Links map[string]string `json:"Links,omitempty"`

	// maintenance expires in
	MaintenanceExpiresIn int32 `json:"MaintenanceExpiresIn,omitempty"`

	// noncompliance reason
	NoncomplianceReason string `json:"NoncomplianceReason,omitempty"`

	// number of machines
	NumberOfMachines int32 `json:"NumberOfMachines,omitempty"`

	// number of nodes
	NumberOfNodes int32 `json:"NumberOfNodes,omitempty"`

	// number of projects
	NumberOfProjects int32 `json:"NumberOfProjects,omitempty"`

	// number of users
	NumberOfUsers int32 `json:"NumberOfUsers,omitempty"`
}

// Validate validates this license status resource
func (m *LicenseStatusResource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastModifiedOn(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LicenseStatusResource) validateLastModifiedOn(formats strfmt.Registry) error {

	if swag.IsZero(m.LastModifiedOn) { // not required
		return nil
	}

	if err := validate.FormatOf("LastModifiedOn", "body", "date-time", m.LastModifiedOn.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LicenseStatusResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LicenseStatusResource) UnmarshalBinary(b []byte) error {
	var res LicenseStatusResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
