// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// VariableResourceScope variable resource scope
// swagger:model variableResourceScope
type VariableResourceScope struct {

	// action
	Action []string `json:"Action"`

	// channel
	Channel []string `json:"Channel"`

	// environment
	Environment []string `json:"Environment"`

	// machine
	Machine []string `json:"Machine"`

	// private
	Private []string `json:"Private"`

	// project
	Project []string `json:"Project"`

	// role
	Role []string `json:"Role"`

	// target role
	TargetRole []string `json:"TargetRole"`

	// tenant
	Tenant []string `json:"Tenant"`

	// tenant tag
	TenantTag []string `json:"TenantTag"`

	// user
	User []string `json:"User"`
}

// Validate validates this variable resource scope
func (m *VariableResourceScope) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VariableResourceScope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VariableResourceScope) UnmarshalBinary(b []byte) error {
	var res VariableResourceScope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
